services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: winnin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/winnin?schema=public'
      PORT: '3000'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
