version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: orders_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: winnin
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d winnin']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: orders_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/winnin?schema=public
      JWT_SECRET: super-secret-CHANGE-ME
      JWT_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 7d
      RUN_SEED: 'true'
    ports:
      - '3000:3000'

volumes:
  pgdata:
